### ISSUE TITLE
question about this project :)

### ISSUE THREAD

**Issue by ORESoftware** [Sequoia/loopback-json-schemas#3]
I just asked this question on SO:

http://stackoverflow.com/questions/39965082/defining-query-parameters-for-basic-crud-operations-in-loopback

looking at this project for answers. My question for you is =>

how do you incorporate this information:

https://github.com/Sequoia/loopback-json-schemas/blob/master/src/loopback-model-query-parameters.json

into your API docs? or, more generally, how do you incorporate the `loopback-model-query-parameters.json` file into your project?

What I am looking to do is modify our swagger.json file so that our API docs reflect the query params that we accept. However, I am guessing that modify the swagger.json file directly is not the best way to proceed...I am guessing that the best way to proceed is to modify some other .json files, and swagger.json will be generated from those. Let me know if you know the answer, thanks!

**Comment by Sequoia** [comment]
I am not sure! I think this is https://github.com/strongloop/loopback question, please try asking there! Sorry I can't help more :)
