### ISSUE TITLE
Schema proposes ACLS principalType in pascal case, when the values should be in upper-case

### ISSUE THREAD

**Issue by Sequoia** [Sequoia/loopback-json-schemas#4]
*migrated from https://github.com/Sequoia/loopback-json-schemas-vscode/issues/1 by @frankorama*

When adding model security using ACLS, the schema states that the principalType should be one of "Application, User, Role", just as the loopback documentation states. However, when using pascal case, the security is not applied. The values need to be one of "APPLICATION, USER, ROLE".

I've found the loopback documentation often has errors when it comes to letter case in their documentation: functions written in pascal case when it should be camel case, etc.

**Comment by fedebaier** [comment]
Why is this still not fixed? It's really annoying.

**Comment by Sequoia** [comment]
@fedebaier because I don't maintain this actively as I don't use loopback much anymore, and this repo therefor lacks contributors. 

I have now invited everyone who's sent a PR to be a contributor so the community is able to keep this going if people want to! :+1:
