### ISSUE TITLE
npm run build failes on Windows (powershell)

### ISSUE THREAD

**Issue by proreact-mj** [Sequoia/loopback-json-schemas#7]
'cp' is not recognized as an internal or external command, operable program or batch file.

Not sure what common practice is for copying files, but I'm guessing 'cp' isn't it :) 

Please share desired approach and I'll create a PR.

**Comment by Sequoia** [comment]
My recommendation is to run the build using cygwin or another *nix type environment. Supporting powershell increases the complexity of this build somewhat and the value of introducing this complexity is not clear.

I'm going to mark this `wontfix`, please reopen if cygwin, gitbash, ubuntu subsystem etc. do not work for you 👍 Thanks!
